apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-secret
  namespace: sonarqube
type: Opaque
data:
  db-username: c29uYXJ1c2Vy  # sonaruser en Base64
  db-password: c29uYXJwYXNz  # sonarpass en Base64

