apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - sonarqube-pvc.yaml
  - sonarqube-deployment.yaml
  - sonarqube-service.yaml
