apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonarqube-user
  namespace: sonarqube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sonarqube
  name: sonarqube-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sonarqube-role-binding
  namespace: sonarqube
subjects:
  - kind: ServiceAccount
    name: sonarqube-user
    namespace: sonarqube
roleRef:
  kind: Role
  name: sonarqube-role
  apiGroup: rbac.authorization.k8s.io
