apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sonarqube-pv.yaml
  - postgresql-pv.yaml
  - sonarqube-pvc.yaml
  - postgresql-pvc.yaml
  - sonarqube-deployment.yaml
  - postgresql-deployment.yaml
  - sonarqube-service.yaml
